# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20171229_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
